/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int32_t add_numbers(int32_t a, int32_t b);
int32_t sub_numbers(int32_t a, int32_t b);
int32_t mul_numbers(int32_t a, int32_t b);
int32_t div_numbers(int32_t a, int32_t b);

int main(void)
{
    printf("-= SVC Calculator =-\n");

    add_numbers(1,2);

    /* Loop forever */
	for(;;);
}

int32_t add_numbers(int32_t a, int32_t b)
{
	printf("\t - On Method %s!\n", __FUNCTION__);

	int res;
	//TODO: Implement SVC instruction to do calculations.
	return res;
}

int32_t sub_numbers(int32_t a, int32_t b)
{
	printf("\t - On Method %s!\n", __FUNCTION__);

	int res;
	//TODO: Implement SVC instruction to do calculations.
	return res;
}

int32_t mul_numbers(int32_t a, int32_t b)
{
	printf("\t - On Method %s!\n", __FUNCTION__);

	int res;
	//TODO: Implement SVC instruction to do calculations.
	return res;
}

int32_t div_numbers(int32_t a, int32_t b)
{
	printf("\t - On Method %s!\n", __FUNCTION__);

	int res;
	//TODO: Implement SVC instruction to do calculations.
	return res;
}
