/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/*
 * SVC code of operations:
 * 		-> 30: Addition
 * 		-> 31: Subtraction
 * 		-> 32: Multiplication
 * 		-> 33: Division
 */


#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void SVC_Handle_c(uint32_t *pBaseStackFrame);
int32_t add_numbers(int32_t a, int32_t b);
int32_t sub_numbers(int32_t a, int32_t b);
int32_t mul_numbers(int32_t a, int32_t b);
int32_t div_numbers(int32_t a, int32_t b);

int main(void)
{
    printf("-= SVC Calculator =-\n");

    add_numbers(1, 2);
    sub_numbers(6, 3);
    mul_numbers(3, 1);
    div_numbers(9, 3);

    /* Loop forever */
	for(;;);
}

__attribute__( ( naked ) ) void SVC_Handler( void )
{
    __asm ("MRS r0,MSP");
    __asm( "B SVC_Handler_c");
}

void SVC_Handler_c(uint32_t *pBaseOfStackFrame)
{
	printf("\t - On Method %s!\n", __FUNCTION__);

}

int32_t add_numbers(int32_t a, int32_t b)
{
	printf("\t - On Method %s!\n", __FUNCTION__);

	int32_t res = 0;

	__asm volatile("SVC #30"); // Calls a SVC instruction with the addition code
	__asm volatile("MOV %0, R0" : "=r"(res) ::); // Retrieves the result from R0 register

	return res;
}

int32_t sub_numbers(int32_t a, int32_t b)
{
	printf("\t - On Method %s!\n", __FUNCTION__);

	int32_t res = 0;

	__asm volatile("SVC #31"); // Calls a SVC instruction with the subtraction code
	__asm volatile("MOV %0, R0" : "=r"(res) ::); // Retrieves the result from R0 register

	return res;
}

int32_t mul_numbers(int32_t a, int32_t b)
{
	printf("\t - On Method %s!\n", __FUNCTION__);

	int32_t res = 0;

	__asm volatile("SVC #32"); // Calls a SVC instruction with the multiplication code
	__asm volatile("MOV %0, R0" : "=r"(res) ::); // Retrieves the result from R0 register

	return res;
}

int32_t div_numbers(int32_t a, int32_t b)
{
	printf("\t - On Method %s!\n", __FUNCTION__);

	int32_t res = 0;

	__asm volatile("SVC #33"); // Calls a SVC instruction with the division code
	__asm volatile("MOV %0, R0" : "=r"(res) ::); // Retrieves the result from R0 register

	return res;
}
